package sqldemo.dao;

import java.util.List;

import sqldemo.model.communicationchannel;

public interface communicationchannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table communicationchannel
     *
     * @mbg.generated Thu Jun 20 20:32:22 CST 2019
     */
    int deleteByPrimaryKey(Integer communicationchannelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table communicationchannel
     *
     * @mbg.generated Thu Jun 20 20:32:22 CST 2019
     */
    int insert(communicationchannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table communicationchannel
     *
     * @mbg.generated Thu Jun 20 20:32:22 CST 2019
     */
    int insertSelective(communicationchannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table communicationchannel
     *
     * @mbg.generated Thu Jun 20 20:32:22 CST 2019
     */
    communicationchannel selectByPrimaryKey(Integer communicationchannelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table communicationchannel
     *
     * @mbg.generated Thu Jun 20 20:32:22 CST 2019
     */
    int updateByPrimaryKeySelective(communicationchannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table communicationchannel
     *
     * @mbg.generated Thu Jun 20 20:32:22 CST 2019
     */
    int updateByPrimaryKey(communicationchannel record);
    
    Integer getCChannelBysd(Integer sid, Integer did);
    
    List<communicationchannel> getAll(String modeltype);
}