package sqldemo.dao;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import sqldemo.model.dataobject;
@Mapper
@Component
public interface dataobjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataobject
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    int deleteByPrimaryKey(Integer dataobjectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataobject
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    int insert(dataobject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataobject
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    int insertSelective(dataobject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataobject
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    dataobject selectByPrimaryKey(Integer dataobjectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataobject
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    int updateByPrimaryKeySelective(dataobject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataobject
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(dataobject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dataobject
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    int updateByPrimaryKey(dataobject record);
    
    dataobject getByFrom(Integer _from);
}