package sqldemo.dao;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import sqldemo.model.device;
@Mapper
@Component
public interface deviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Sun May 05 20:04:36 CST 2019
     */
    int deleteByPrimaryKey(Integer deviceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Sun May 05 20:04:36 CST 2019
     */
    int insert(device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Sun May 05 20:04:36 CST 2019
     */
    int insertSelective(device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Sun May 05 20:04:36 CST 2019
     */
    device selectByPrimaryKey(Integer deviceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Sun May 05 20:04:36 CST 2019
     */
    int updateByPrimaryKeySelective(device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device
     *
     * @mbg.generated Sun May 05 20:04:36 CST 2019
     */
    int updateByPrimaryKey(device record);
}