package sqldemo.dao;

import sqldemo.model.elementmap;

public interface elementmapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elementmap
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elementmap
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    int insert(elementmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elementmap
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    int insertSelective(elementmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elementmap
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    elementmap selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elementmap
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    int updateByPrimaryKeySelective(elementmap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table elementmap
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    int updateByPrimaryKey(elementmap record);
}