package sqldemo.dao;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import sqldemo.model.slkstate;
@Mapper
@Component
public interface slkstateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slkstate
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slkstate
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    int insert(slkstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slkstate
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    int insertSelective(slkstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slkstate
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    slkstate selectByPrimaryKey(Integer id);
    slkstate selectByTask(Integer taskid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slkstate
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    int updateByPrimaryKeySelective(slkstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slkstate
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    int updateByPrimaryKey(slkstate record);
}