package sqldemo.dao;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import sqldemo.model.transition;
@Mapper
@Component
public interface transitionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transition
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    int deleteByPrimaryKey(Integer transitionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transition
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    int insert(transition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transition
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    int insertSelective(transition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transition
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    transition selectByPrimaryKey(Integer transitionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transition
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    int updateByPrimaryKeySelective(transition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transition
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    int updateByPrimaryKey(transition record);
}