package sqldemo.model;

public class _event {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.EventID
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    private Integer eventid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.At
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    private String at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.Name
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.FlowtriggerID
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    private Integer flowtriggerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.occurrence
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    private Integer occurrence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event.attached
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    private Integer attached;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.EventID
     *
     * @return the value of event.EventID
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    public Integer getEventid() {
        return eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.EventID
     *
     * @param eventid the value for event.EventID
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    public void setEventid(Integer eventid) {
        this.eventid = eventid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.At
     *
     * @return the value of event.At
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    public String getAt() {
        return at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.At
     *
     * @param at the value for event.At
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    public void setAt(String at) {
        this.at = at == null ? null : at.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.Name
     *
     * @return the value of event.Name
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.Name
     *
     * @param name the value for event.Name
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.FlowtriggerID
     *
     * @return the value of event.FlowtriggerID
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    public Integer getFlowtriggerid() {
        return flowtriggerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.FlowtriggerID
     *
     * @param flowtriggerid the value for event.FlowtriggerID
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    public void setFlowtriggerid(Integer flowtriggerid) {
        this.flowtriggerid = flowtriggerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.occurrence
     *
     * @return the value of event.occurrence
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    public Integer getOccurrence() {
        return occurrence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.occurrence
     *
     * @param occurrence the value for event.occurrence
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    public void setOccurrence(Integer occurrence) {
        this.occurrence = occurrence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event.attached
     *
     * @return the value of event.attached
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    public Integer getAttached() {
        return attached;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event.attached
     *
     * @param attached the value for event.attached
     *
     * @mbg.generated Mon Apr 29 16:50:42 CST 2019
     */
    public void setAttached(Integer attached) {
        this.attached = attached;
    }
}