package sqldemo.model;

public class _exception {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exception.ExceptionID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    private Integer exceptionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exception.Name
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exception.Type
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exception.CommunicationchannelID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    private Integer communicationchannelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exception.FaultmitigationID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    private Integer faultmitigationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exception.FaultdetectiionID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    private Integer faultdetectiionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exception.RequirementID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    private Integer requirementid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exception.StateID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    private Integer stateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exception.componentID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    private Integer componentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exception.linkpointid
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    private Integer linkpointid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception.ExceptionID
     *
     * @return the value of exception.ExceptionID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public Integer getExceptionid() {
        return exceptionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception.ExceptionID
     *
     * @param exceptionid the value for exception.ExceptionID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public void setExceptionid(Integer exceptionid) {
        this.exceptionid = exceptionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception.Name
     *
     * @return the value of exception.Name
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception.Name
     *
     * @param name the value for exception.Name
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception.Type
     *
     * @return the value of exception.Type
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception.Type
     *
     * @param type the value for exception.Type
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception.CommunicationchannelID
     *
     * @return the value of exception.CommunicationchannelID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public Integer getCommunicationchannelid() {
        return communicationchannelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception.CommunicationchannelID
     *
     * @param communicationchannelid the value for exception.CommunicationchannelID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public void setCommunicationchannelid(Integer communicationchannelid) {
        this.communicationchannelid = communicationchannelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception.FaultmitigationID
     *
     * @return the value of exception.FaultmitigationID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public Integer getFaultmitigationid() {
        return faultmitigationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception.FaultmitigationID
     *
     * @param faultmitigationid the value for exception.FaultmitigationID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public void setFaultmitigationid(Integer faultmitigationid) {
        this.faultmitigationid = faultmitigationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception.FaultdetectiionID
     *
     * @return the value of exception.FaultdetectiionID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public Integer getFaultdetectiionid() {
        return faultdetectiionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception.FaultdetectiionID
     *
     * @param faultdetectiionid the value for exception.FaultdetectiionID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public void setFaultdetectiionid(Integer faultdetectiionid) {
        this.faultdetectiionid = faultdetectiionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception.RequirementID
     *
     * @return the value of exception.RequirementID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public Integer getRequirementid() {
        return requirementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception.RequirementID
     *
     * @param requirementid the value for exception.RequirementID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public void setRequirementid(Integer requirementid) {
        this.requirementid = requirementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception.StateID
     *
     * @return the value of exception.StateID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public Integer getStateid() {
        return stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception.StateID
     *
     * @param stateid the value for exception.StateID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public void setStateid(Integer stateid) {
        this.stateid = stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception.componentID
     *
     * @return the value of exception.componentID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public Integer getComponentid() {
        return componentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception.componentID
     *
     * @param componentid the value for exception.componentID
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public void setComponentid(Integer componentid) {
        this.componentid = componentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exception.linkpointid
     *
     * @return the value of exception.linkpointid
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public Integer getLinkpointid() {
        return linkpointid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exception.linkpointid
     *
     * @param linkpointid the value for exception.linkpointid
     *
     * @mbg.generated Sun Jun 23 16:28:00 CST 2019
     */
    public void setLinkpointid(Integer linkpointid) {
        this.linkpointid = linkpointid;
    }
}