package sqldemo.model;

public class _partition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _partition.PartitionID
     *
     * @mbg.generated Wed May 15 00:29:27 CST 2019
     */
    private Integer partitionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _partition.Memory
     *
     * @mbg.generated Wed May 15 00:29:27 CST 2019
     */
    private Integer memory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _partition.rtosid
     *
     * @mbg.generated Wed May 15 00:29:27 CST 2019
     */
    private Integer rtosid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _partition.PartitionID
     *
     * @return the value of _partition.PartitionID
     *
     * @mbg.generated Wed May 15 00:29:27 CST 2019
     */
    public Integer getPartitionid() {
        return partitionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _partition.PartitionID
     *
     * @param partitionid the value for _partition.PartitionID
     *
     * @mbg.generated Wed May 15 00:29:27 CST 2019
     */
    public void setPartitionid(Integer partitionid) {
        this.partitionid = partitionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _partition.Memory
     *
     * @return the value of _partition.Memory
     *
     * @mbg.generated Wed May 15 00:29:27 CST 2019
     */
    public Integer getMemory() {
        return memory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _partition.Memory
     *
     * @param memory the value for _partition.Memory
     *
     * @mbg.generated Wed May 15 00:29:27 CST 2019
     */
    public void setMemory(Integer memory) {
        this.memory = memory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _partition.rtosid
     *
     * @return the value of _partition.rtosid
     *
     * @mbg.generated Wed May 15 00:29:27 CST 2019
     */
    public Integer getRtosid() {
        return rtosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _partition.rtosid
     *
     * @param rtosid the value for _partition.rtosid
     *
     * @mbg.generated Wed May 15 00:29:27 CST 2019
     */
    public void setRtosid(Integer rtosid) {
        this.rtosid = rtosid;
    }
}