package sqldemo.model;

public class _state {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.StateID
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    private Integer stateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.Name
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.ComponentID
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    private Integer componentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.entry
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    private Integer entry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.TaskID
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    private Integer taskid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.StateID
     *
     * @return the value of state.StateID
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    public Integer getStateid() {
        return stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.StateID
     *
     * @param stateid the value for state.StateID
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    public void setStateid(Integer stateid) {
        this.stateid = stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.Name
     *
     * @return the value of state.Name
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.Name
     *
     * @param name the value for state.Name
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.ComponentID
     *
     * @return the value of state.ComponentID
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    public Integer getComponentid() {
        return componentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.ComponentID
     *
     * @param componentid the value for state.ComponentID
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    public void setComponentid(Integer componentid) {
        this.componentid = componentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.entry
     *
     * @return the value of state.entry
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    public Integer getEntry() {
        return entry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.entry
     *
     * @param entry the value for state.entry
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    public void setEntry(Integer entry) {
        this.entry = entry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.TaskID
     *
     * @return the value of state.TaskID
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    public Integer getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.TaskID
     *
     * @param taskid the value for state.TaskID
     *
     * @mbg.generated Mon Apr 29 17:41:06 CST 2019
     */
    public void setTaskid(Integer taskid) {
        this.taskid = taskid;
    }
}