package sqldemo.model;
public class _task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.TaskID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    private Integer taskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.Deadline
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    private String deadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.Name
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.Offset
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    private String offset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.Period
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.Priority
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.Required_mem
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    private Integer requiredMem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.Wcet
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    private String wcet;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.Design2reqtraceID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    private Integer design2reqtraceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.PartitionID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    private Integer partitionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.StateID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    private Integer stateid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.TasknodeID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    private Integer tasknodeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.TaskscheduleID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    private Integer taskscheduleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.fatherid
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    private Integer fatherid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.TaskID
     *
     * @return the value of task.TaskID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public Integer getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.TaskID
     *
     * @param taskid the value for task.TaskID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public void setTaskid(Integer taskid) {
        this.taskid = taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.Deadline
     *
     * @return the value of task.Deadline
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public String getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.Deadline
     *
     * @param deadline the value for task.Deadline
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public void setDeadline(String deadline) {
        this.deadline = deadline == null ? null : deadline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.Name
     *
     * @return the value of task.Name
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.Name
     *
     * @param name the value for task.Name
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.Offset
     *
     * @return the value of task.Offset
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public String getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.Offset
     *
     * @param offset the value for task.Offset
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public void setOffset(String offset) {
        this.offset = offset == null ? null : offset.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.Period
     *
     * @return the value of task.Period
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.Period
     *
     * @param period the value for task.Period
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.Priority
     *
     * @return the value of task.Priority
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.Priority
     *
     * @param priority the value for task.Priority
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.Required_mem
     *
     * @return the value of task.Required_mem
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public Integer getRequiredMem() {
        return requiredMem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.Required_mem
     *
     * @param requiredMem the value for task.Required_mem
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public void setRequiredMem(Integer requiredMem) {
        this.requiredMem = requiredMem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.Wcet
     *
     * @return the value of task.Wcet
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public String getWcet() {
        return wcet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.Wcet
     *
     * @param wcet the value for task.Wcet
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public void setWcet(String wcet) {
        this.wcet = wcet == null ? null : wcet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.Design2reqtraceID
     *
     * @return the value of task.Design2reqtraceID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public Integer getDesign2reqtraceid() {
        return design2reqtraceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.Design2reqtraceID
     *
     * @param design2reqtraceid the value for task.Design2reqtraceID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public void setDesign2reqtraceid(Integer design2reqtraceid) {
        this.design2reqtraceid = design2reqtraceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.PartitionID
     *
     * @return the value of task.PartitionID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public Integer getPartitionid() {
        return partitionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.PartitionID
     *
     * @param partitionid the value for task.PartitionID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public void setPartitionid(Integer partitionid) {
        this.partitionid = partitionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.StateID
     *
     * @return the value of task.StateID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public Integer getStateid() {
        return stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.StateID
     *
     * @param stateid the value for task.StateID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public void setStateid(Integer stateid) {
        this.stateid = stateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.TasknodeID
     *
     * @return the value of task.TasknodeID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public Integer getTasknodeid() {
        return tasknodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.TasknodeID
     *
     * @param tasknodeid the value for task.TasknodeID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public void setTasknodeid(Integer tasknodeid) {
        this.tasknodeid = tasknodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.TaskscheduleID
     *
     * @return the value of task.TaskscheduleID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public Integer getTaskscheduleid() {
        return taskscheduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.TaskscheduleID
     *
     * @param taskscheduleid the value for task.TaskscheduleID
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public void setTaskscheduleid(Integer taskscheduleid) {
        this.taskscheduleid = taskscheduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.fatherid
     *
     * @return the value of task.fatherid
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public Integer getFatherid() {
        return fatherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.fatherid
     *
     * @param fatherid the value for task.fatherid
     *
     * @mbg.generated Fri Jun 07 09:53:00 CST 2019
     */
    public void setFatherid(Integer fatherid) {
        this.fatherid = fatherid;
    }
}