package sqldemo.model;
public class communicationchannel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column communicationchannel.CommunicationchannelID
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    private Integer communicationchannelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column communicationchannel.Delay
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    private String delay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column communicationchannel.Mode
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    private String mode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column communicationchannel.Name
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column communicationchannel.sourceid
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    private Integer sourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column communicationchannel.destid
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    private Integer destid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column communicationchannel.type
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column communicationchannel.modeltype
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    private String modeltype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column communicationchannel.CommunicationchannelID
     *
     * @return the value of communicationchannel.CommunicationchannelID
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    public Integer getCommunicationchannelid() {
        return communicationchannelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column communicationchannel.CommunicationchannelID
     *
     * @param communicationchannelid the value for communicationchannel.CommunicationchannelID
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    public void setCommunicationchannelid(Integer communicationchannelid) {
        this.communicationchannelid = communicationchannelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column communicationchannel.Delay
     *
     * @return the value of communicationchannel.Delay
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    public String getDelay() {
        return delay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column communicationchannel.Delay
     *
     * @param delay the value for communicationchannel.Delay
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    public void setDelay(String delay) {
        this.delay = delay == null ? null : delay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column communicationchannel.Mode
     *
     * @return the value of communicationchannel.Mode
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    public String getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column communicationchannel.Mode
     *
     * @param mode the value for communicationchannel.Mode
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    public void setMode(String mode) {
        this.mode = mode == null ? null : mode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column communicationchannel.Name
     *
     * @return the value of communicationchannel.Name
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column communicationchannel.Name
     *
     * @param name the value for communicationchannel.Name
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column communicationchannel.sourceid
     *
     * @return the value of communicationchannel.sourceid
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    public Integer getSourceid() {
        return sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column communicationchannel.sourceid
     *
     * @param sourceid the value for communicationchannel.sourceid
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    public void setSourceid(Integer sourceid) {
        this.sourceid = sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column communicationchannel.destid
     *
     * @return the value of communicationchannel.destid
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    public Integer getDestid() {
        return destid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column communicationchannel.destid
     *
     * @param destid the value for communicationchannel.destid
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    public void setDestid(Integer destid) {
        this.destid = destid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column communicationchannel.type
     *
     * @return the value of communicationchannel.type
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column communicationchannel.type
     *
     * @param type the value for communicationchannel.type
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column communicationchannel.modeltype
     *
     * @return the value of communicationchannel.modeltype
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    public String getModeltype() {
        return modeltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column communicationchannel.modeltype
     *
     * @param modeltype the value for communicationchannel.modeltype
     *
     * @mbg.generated Thu Jun 20 20:41:29 CST 2019
     */
    public void setModeltype(String modeltype) {
        this.modeltype = modeltype == null ? null : modeltype.trim();
    }
}