package sqldemo.model;
public class componenttransition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column componenttransition.idcomponenttransition
     *
     * @mbg.generated Thu Jun 20 17:28:54 CST 2019
     */
    private Integer idcomponenttransition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column componenttransition.componentid
     *
     * @mbg.generated Thu Jun 20 17:28:54 CST 2019
     */
    private String componentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column componenttransition.transitionid
     *
     * @mbg.generated Thu Jun 20 17:28:54 CST 2019
     */
    private String transitionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column componenttransition.idcomponenttransition
     *
     * @return the value of componenttransition.idcomponenttransition
     *
     * @mbg.generated Thu Jun 20 17:28:54 CST 2019
     */
    public Integer getIdcomponenttransition() {
        return idcomponenttransition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column componenttransition.idcomponenttransition
     *
     * @param idcomponenttransition the value for componenttransition.idcomponenttransition
     *
     * @mbg.generated Thu Jun 20 17:28:54 CST 2019
     */
    public void setIdcomponenttransition(Integer idcomponenttransition) {
        this.idcomponenttransition = idcomponenttransition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column componenttransition.componentid
     *
     * @return the value of componenttransition.componentid
     *
     * @mbg.generated Thu Jun 20 17:28:54 CST 2019
     */
    public String getComponentid() {
        return componentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column componenttransition.componentid
     *
     * @param componentid the value for componenttransition.componentid
     *
     * @mbg.generated Thu Jun 20 17:28:54 CST 2019
     */
    public void setComponentid(String componentid) {
        this.componentid = componentid == null ? null : componentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column componenttransition.transitionid
     *
     * @return the value of componenttransition.transitionid
     *
     * @mbg.generated Thu Jun 20 17:28:54 CST 2019
     */
    public String getTransitionid() {
        return transitionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column componenttransition.transitionid
     *
     * @param transitionid the value for componenttransition.transitionid
     *
     * @mbg.generated Thu Jun 20 17:28:54 CST 2019
     */
    public void setTransitionid(String transitionid) {
        this.transitionid = transitionid == null ? null : transitionid.trim();
    }
}