package sqldemo.model;
public class connections {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connections.idconnections
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    private Integer idconnections;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connections.connectionType
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    private String connectiontype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connections.startcomponentID
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    private Integer startcomponentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connections.startinterface
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    private String startinterface;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connections.endcomponentID
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    private Integer endcomponentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connections.endinterface
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    private String endinterface;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column connections.fathercmpid
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    private String fathercmpid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connections.idconnections
     *
     * @return the value of connections.idconnections
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    public Integer getIdconnections() {
        return idconnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connections.idconnections
     *
     * @param idconnections the value for connections.idconnections
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    public void setIdconnections(Integer idconnections) {
        this.idconnections = idconnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connections.connectionType
     *
     * @return the value of connections.connectionType
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    public String getConnectiontype() {
        return connectiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connections.connectionType
     *
     * @param connectiontype the value for connections.connectionType
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    public void setConnectiontype(String connectiontype) {
        this.connectiontype = connectiontype == null ? null : connectiontype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connections.startcomponentID
     *
     * @return the value of connections.startcomponentID
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    public Integer getStartcomponentid() {
        return startcomponentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connections.startcomponentID
     *
     * @param startcomponentid the value for connections.startcomponentID
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    public void setStartcomponentid(Integer startcomponentid) {
        this.startcomponentid = startcomponentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connections.startinterface
     *
     * @return the value of connections.startinterface
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    public String getStartinterface() {
        return startinterface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connections.startinterface
     *
     * @param startinterface the value for connections.startinterface
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    public void setStartinterface(String startinterface) {
        this.startinterface = startinterface == null ? null : startinterface.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connections.endcomponentID
     *
     * @return the value of connections.endcomponentID
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    public Integer getEndcomponentid() {
        return endcomponentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connections.endcomponentID
     *
     * @param endcomponentid the value for connections.endcomponentID
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    public void setEndcomponentid(Integer endcomponentid) {
        this.endcomponentid = endcomponentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connections.endinterface
     *
     * @return the value of connections.endinterface
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    public String getEndinterface() {
        return endinterface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connections.endinterface
     *
     * @param endinterface the value for connections.endinterface
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    public void setEndinterface(String endinterface) {
        this.endinterface = endinterface == null ? null : endinterface.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column connections.fathercmpid
     *
     * @return the value of connections.fathercmpid
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    public String getFathercmpid() {
        return fathercmpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column connections.fathercmpid
     *
     * @param fathercmpid the value for connections.fathercmpid
     *
     * @mbg.generated Thu Jun 27 10:12:55 CST 2019
     */
    public void setFathercmpid(String fathercmpid) {
        this.fathercmpid = fathercmpid == null ? null : fathercmpid.trim();
    }
}