package sqldemo.model;
public class dataobject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataobject.DataobjectID
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    private Integer dataobjectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataobject.Invariant
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    private String invariant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataobject.Name
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataobject.to
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    private Integer _to;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataobject.from
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    private Integer _from;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataobject.SoftcomponentID
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    private Integer softcomponentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataobject.RequirementID
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    private Integer requirementid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataobject.datatype
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    private String datatype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataobject.ReferencedDataobjectID
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    private byte[] referenceddataobjectid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataobject.DataobjectID
     *
     * @return the value of dataobject.DataobjectID
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public Integer getDataobjectid() {
        return dataobjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataobject.DataobjectID
     *
     * @param dataobjectid the value for dataobject.DataobjectID
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public void setDataobjectid(Integer dataobjectid) {
        this.dataobjectid = dataobjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataobject.Invariant
     *
     * @return the value of dataobject.Invariant
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public String getInvariant() {
        return invariant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataobject.Invariant
     *
     * @param invariant the value for dataobject.Invariant
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public void setInvariant(String invariant) {
        this.invariant = invariant == null ? null : invariant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataobject.Name
     *
     * @return the value of dataobject.Name
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataobject.Name
     *
     * @param name the value for dataobject.Name
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataobject.to
     *
     * @return the value of dataobject.to
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public Integer getTo() {
        return _to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataobject.to
     *
     * @param to the value for dataobject.to
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public void setTo(Integer _to) {
        this._to = _to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataobject.from
     *
     * @return the value of dataobject.from
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public Integer getFrom() {
        return _from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataobject.from
     *
     * @param from the value for dataobject.from
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public void setFrom(Integer _from) {
        this._from = _from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataobject.SoftcomponentID
     *
     * @return the value of dataobject.SoftcomponentID
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public Integer getSoftcomponentid() {
        return softcomponentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataobject.SoftcomponentID
     *
     * @param softcomponentid the value for dataobject.SoftcomponentID
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public void setSoftcomponentid(Integer softcomponentid) {
        this.softcomponentid = softcomponentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataobject.RequirementID
     *
     * @return the value of dataobject.RequirementID
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public Integer getRequirementid() {
        return requirementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataobject.RequirementID
     *
     * @param requirementid the value for dataobject.RequirementID
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public void setRequirementid(Integer requirementid) {
        this.requirementid = requirementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataobject.datatype
     *
     * @return the value of dataobject.datatype
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public String getDatatype() {
        return datatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataobject.datatype
     *
     * @param datatype the value for dataobject.datatype
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public void setDatatype(String datatype) {
        this.datatype = datatype == null ? null : datatype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dataobject.ReferencedDataobjectID
     *
     * @return the value of dataobject.ReferencedDataobjectID
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public byte[] getReferenceddataobjectid() {
        return referenceddataobjectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dataobject.ReferencedDataobjectID
     *
     * @param referenceddataobjectid the value for dataobject.ReferencedDataobjectID
     *
     * @mbg.generated Mon Jun 17 21:27:04 CST 2019
     */
    public void setReferenceddataobjectid(byte[] referenceddataobjectid) {
        this.referenceddataobjectid = referenceddataobjectid;
    }
}