package sqldemo.model;
public class elementmap {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elementmap.id
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elementmap.sourcemodelType
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    private String sourcemodeltype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elementmap.sourcename
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    private String sourcename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elementmap.sourceid
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    private String sourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elementmap.corrmodeltype
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    private String corrmodeltype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elementmap.corrname
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    private String corrname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elementmap.corrid
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    private String corrid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column elementmap.projectid
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    private String projectid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elementmap.id
     *
     * @return the value of elementmap.id
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elementmap.id
     *
     * @param id the value for elementmap.id
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elementmap.sourcemodelType
     *
     * @return the value of elementmap.sourcemodelType
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    public String getSourcemodeltype() {
        return sourcemodeltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elementmap.sourcemodelType
     *
     * @param sourcemodeltype the value for elementmap.sourcemodelType
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    public void setSourcemodeltype(String sourcemodeltype) {
        this.sourcemodeltype = sourcemodeltype == null ? null : sourcemodeltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elementmap.sourcename
     *
     * @return the value of elementmap.sourcename
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    public String getSourcename() {
        return sourcename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elementmap.sourcename
     *
     * @param sourcename the value for elementmap.sourcename
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    public void setSourcename(String sourcename) {
        this.sourcename = sourcename == null ? null : sourcename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elementmap.sourceid
     *
     * @return the value of elementmap.sourceid
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    public String getSourceid() {
        return sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elementmap.sourceid
     *
     * @param sourceid the value for elementmap.sourceid
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    public void setSourceid(String sourceid) {
        this.sourceid = sourceid == null ? null : sourceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elementmap.corrmodeltype
     *
     * @return the value of elementmap.corrmodeltype
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    public String getCorrmodeltype() {
        return corrmodeltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elementmap.corrmodeltype
     *
     * @param corrmodeltype the value for elementmap.corrmodeltype
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    public void setCorrmodeltype(String corrmodeltype) {
        this.corrmodeltype = corrmodeltype == null ? null : corrmodeltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elementmap.corrname
     *
     * @return the value of elementmap.corrname
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    public String getCorrname() {
        return corrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elementmap.corrname
     *
     * @param corrname the value for elementmap.corrname
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    public void setCorrname(String corrname) {
        this.corrname = corrname == null ? null : corrname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elementmap.corrid
     *
     * @return the value of elementmap.corrid
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    public String getCorrid() {
        return corrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elementmap.corrid
     *
     * @param corrid the value for elementmap.corrid
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    public void setCorrid(String corrid) {
        this.corrid = corrid == null ? null : corrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column elementmap.projectid
     *
     * @return the value of elementmap.projectid
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    public String getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column elementmap.projectid
     *
     * @param projectid the value for elementmap.projectid
     *
     * @mbg.generated Wed May 29 14:40:47 CST 2019
     */
    public void setProjectid(String projectid) {
        this.projectid = projectid == null ? null : projectid.trim();
    }
}