package sqldemo.model;
public class linkpoint {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkpoint.LinkpointID
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    private Integer linkpointid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkpoint.Name
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkpoint.Period
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkpoint.Postcondition
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    private String postcondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkpoint.Precondition
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    private String precondition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkpoint.CommunicationchannelID
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    private Integer communicationchannelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkpoint.channel
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    private Integer channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkpoint.RequirementID
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    private Integer requirementid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column linkpoint.modelType
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    private String modeltype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkpoint.LinkpointID
     *
     * @return the value of linkpoint.LinkpointID
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public Integer getLinkpointid() {
        return linkpointid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkpoint.LinkpointID
     *
     * @param linkpointid the value for linkpoint.LinkpointID
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public void setLinkpointid(Integer linkpointid) {
        this.linkpointid = linkpointid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkpoint.Name
     *
     * @return the value of linkpoint.Name
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkpoint.Name
     *
     * @param name the value for linkpoint.Name
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkpoint.Period
     *
     * @return the value of linkpoint.Period
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkpoint.Period
     *
     * @param period the value for linkpoint.Period
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkpoint.Postcondition
     *
     * @return the value of linkpoint.Postcondition
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public String getPostcondition() {
        return postcondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkpoint.Postcondition
     *
     * @param postcondition the value for linkpoint.Postcondition
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public void setPostcondition(String postcondition) {
        this.postcondition = postcondition == null ? null : postcondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkpoint.Precondition
     *
     * @return the value of linkpoint.Precondition
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public String getPrecondition() {
        return precondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkpoint.Precondition
     *
     * @param precondition the value for linkpoint.Precondition
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public void setPrecondition(String precondition) {
        this.precondition = precondition == null ? null : precondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkpoint.CommunicationchannelID
     *
     * @return the value of linkpoint.CommunicationchannelID
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public Integer getCommunicationchannelid() {
        return communicationchannelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkpoint.CommunicationchannelID
     *
     * @param communicationchannelid the value for linkpoint.CommunicationchannelID
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public void setCommunicationchannelid(Integer communicationchannelid) {
        this.communicationchannelid = communicationchannelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkpoint.channel
     *
     * @return the value of linkpoint.channel
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public Integer getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkpoint.channel
     *
     * @param channel the value for linkpoint.channel
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public void setChannel(Integer channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkpoint.RequirementID
     *
     * @return the value of linkpoint.RequirementID
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public Integer getRequirementid() {
        return requirementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkpoint.RequirementID
     *
     * @param requirementid the value for linkpoint.RequirementID
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public void setRequirementid(Integer requirementid) {
        this.requirementid = requirementid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column linkpoint.modelType
     *
     * @return the value of linkpoint.modelType
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public String getModeltype() {
        return modeltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column linkpoint.modelType
     *
     * @param modeltype the value for linkpoint.modelType
     *
     * @mbg.generated Wed May 29 15:04:20 CST 2019
     */
    public void setModeltype(String modeltype) {
        this.modeltype = modeltype == null ? null : modeltype.trim();
    }
}