package sqldemo.model;
public class processor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processor.ProcessorID
     *
     * @mbg.generated Tue Jun 04 16:05:19 CST 2019
     */
    private Integer processorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processor.Cores
     *
     * @mbg.generated Tue Jun 04 16:05:19 CST 2019
     */
    private Integer cores;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processor.Freq
     *
     * @mbg.generated Tue Jun 04 16:05:19 CST 2019
     */
    private Integer freq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processor.Type
     *
     * @mbg.generated Tue Jun 04 16:05:19 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column processor.RtosID
     *
     * @mbg.generated Tue Jun 04 16:05:19 CST 2019
     */
    private Integer rtosid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column processor.ProcessorID
     *
     * @return the value of processor.ProcessorID
     *
     * @mbg.generated Tue Jun 04 16:05:19 CST 2019
     */
    public Integer getProcessorid() {
        return processorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column processor.ProcessorID
     *
     * @param processorid the value for processor.ProcessorID
     *
     * @mbg.generated Tue Jun 04 16:05:19 CST 2019
     */
    public void setProcessorid(Integer processorid) {
        this.processorid = processorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column processor.Cores
     *
     * @return the value of processor.Cores
     *
     * @mbg.generated Tue Jun 04 16:05:19 CST 2019
     */
    public Integer getCores() {
        return cores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column processor.Cores
     *
     * @param cores the value for processor.Cores
     *
     * @mbg.generated Tue Jun 04 16:05:19 CST 2019
     */
    public void setCores(Integer cores) {
        this.cores = cores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column processor.Freq
     *
     * @return the value of processor.Freq
     *
     * @mbg.generated Tue Jun 04 16:05:19 CST 2019
     */
    public Integer getFreq() {
        return freq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column processor.Freq
     *
     * @param freq the value for processor.Freq
     *
     * @mbg.generated Tue Jun 04 16:05:19 CST 2019
     */
    public void setFreq(Integer freq) {
        this.freq = freq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column processor.Type
     *
     * @return the value of processor.Type
     *
     * @mbg.generated Tue Jun 04 16:05:19 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column processor.Type
     *
     * @param type the value for processor.Type
     *
     * @mbg.generated Tue Jun 04 16:05:19 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column processor.RtosID
     *
     * @return the value of processor.RtosID
     *
     * @mbg.generated Tue Jun 04 16:05:19 CST 2019
     */
    public Integer getRtosid() {
        return rtosid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column processor.RtosID
     *
     * @param rtosid the value for processor.RtosID
     *
     * @mbg.generated Tue Jun 04 16:05:19 CST 2019
     */
    public void setRtosid(Integer rtosid) {
        this.rtosid = rtosid;
    }
}