package sqldemo.model;
public class slkstate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slkstate.ID
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slkstate.taskid
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    private String taskid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slkstate.exitinfo
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    private String exitinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slkstate.slkstatecol
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    private String slkstatecol;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slkstate.ID
     *
     * @return the value of slkstate.ID
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slkstate.ID
     *
     * @param id the value for slkstate.ID
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slkstate.taskid
     *
     * @return the value of slkstate.taskid
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    public String getTaskid() {
        return taskid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slkstate.taskid
     *
     * @param taskid the value for slkstate.taskid
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    public void setTaskid(String taskid) {
        this.taskid = taskid == null ? null : taskid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slkstate.exitinfo
     *
     * @return the value of slkstate.exitinfo
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    public String getExitinfo() {
        return exitinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slkstate.exitinfo
     *
     * @param exitinfo the value for slkstate.exitinfo
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    public void setExitinfo(String exitinfo) {
        this.exitinfo = exitinfo == null ? null : exitinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slkstate.slkstatecol
     *
     * @return the value of slkstate.slkstatecol
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    public String getSlkstatecol() {
        return slkstatecol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slkstate.slkstatecol
     *
     * @param slkstatecol the value for slkstate.slkstatecol
     *
     * @mbg.generated Wed Jun 26 21:06:18 CST 2019
     */
    public void setSlkstatecol(String slkstatecol) {
        this.slkstatecol = slkstatecol == null ? null : slkstatecol.trim();
    }
}