package sqldemo.model;
public class taskschedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskschedule.TaskscheduleID
     *
     * @mbg.generated Tue May 28 10:49:45 CST 2019
     */
    private Integer taskscheduleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskschedule.Schedulable
     *
     * @mbg.generated Tue May 28 10:49:45 CST 2019
     */
    private Boolean schedulable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskschedule.Slot
     *
     * @mbg.generated Tue May 28 10:49:45 CST 2019
     */
    private String slot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taskschedule.Strategy
     *
     * @mbg.generated Tue May 28 10:49:45 CST 2019
     */
    private String strategy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskschedule.TaskscheduleID
     *
     * @return the value of taskschedule.TaskscheduleID
     *
     * @mbg.generated Tue May 28 10:49:45 CST 2019
     */
    public Integer getTaskscheduleid() {
        return taskscheduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskschedule.TaskscheduleID
     *
     * @param taskscheduleid the value for taskschedule.TaskscheduleID
     *
     * @mbg.generated Tue May 28 10:49:45 CST 2019
     */
    public void setTaskscheduleid(Integer taskscheduleid) {
        this.taskscheduleid = taskscheduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskschedule.Schedulable
     *
     * @return the value of taskschedule.Schedulable
     *
     * @mbg.generated Tue May 28 10:49:45 CST 2019
     */
    public Boolean getSchedulable() {
        return schedulable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskschedule.Schedulable
     *
     * @param schedulable the value for taskschedule.Schedulable
     *
     * @mbg.generated Tue May 28 10:49:45 CST 2019
     */
    public void setSchedulable(Boolean schedulable) {
        this.schedulable = schedulable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskschedule.Slot
     *
     * @return the value of taskschedule.Slot
     *
     * @mbg.generated Tue May 28 10:49:45 CST 2019
     */
    public String getSlot() {
        return slot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskschedule.Slot
     *
     * @param slot the value for taskschedule.Slot
     *
     * @mbg.generated Tue May 28 10:49:45 CST 2019
     */
    public void setSlot(String slot) {
        this.slot = slot == null ? null : slot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taskschedule.Strategy
     *
     * @return the value of taskschedule.Strategy
     *
     * @mbg.generated Tue May 28 10:49:45 CST 2019
     */
    public String getStrategy() {
        return strategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taskschedule.Strategy
     *
     * @param strategy the value for taskschedule.Strategy
     *
     * @mbg.generated Tue May 28 10:49:45 CST 2019
     */
    public void setStrategy(String strategy) {
        this.strategy = strategy == null ? null : strategy.trim();
    }
}