package sqldemo.model;
public class transitionstate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transitionstate.id
     *
     * @mbg.generated Thu Jun 20 16:53:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transitionstate.sourceid
     *
     * @mbg.generated Thu Jun 20 16:53:59 CST 2019
     */
    private Integer sourceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transitionstate.outid
     *
     * @mbg.generated Thu Jun 20 16:53:59 CST 2019
     */
    private Integer outid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transitionstate.transitionid
     *
     * @mbg.generated Thu Jun 20 16:53:59 CST 2019
     */
    private Integer transitionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transitionstate.id
     *
     * @return the value of transitionstate.id
     *
     * @mbg.generated Thu Jun 20 16:53:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transitionstate.id
     *
     * @param id the value for transitionstate.id
     *
     * @mbg.generated Thu Jun 20 16:53:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transitionstate.sourceid
     *
     * @return the value of transitionstate.sourceid
     *
     * @mbg.generated Thu Jun 20 16:53:59 CST 2019
     */
    public Integer getSourceid() {
        return sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transitionstate.sourceid
     *
     * @param sourceid the value for transitionstate.sourceid
     *
     * @mbg.generated Thu Jun 20 16:53:59 CST 2019
     */
    public void setSourceid(Integer sourceid) {
        this.sourceid = sourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transitionstate.outid
     *
     * @return the value of transitionstate.outid
     *
     * @mbg.generated Thu Jun 20 16:53:59 CST 2019
     */
    public Integer getOutid() {
        return outid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transitionstate.outid
     *
     * @param outid the value for transitionstate.outid
     *
     * @mbg.generated Thu Jun 20 16:53:59 CST 2019
     */
    public void setOutid(Integer outid) {
        this.outid = outid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transitionstate.transitionid
     *
     * @return the value of transitionstate.transitionid
     *
     * @mbg.generated Thu Jun 20 16:53:59 CST 2019
     */
    public Integer getTransitionid() {
        return transitionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transitionstate.transitionid
     *
     * @param transitionid the value for transitionstate.transitionid
     *
     * @mbg.generated Thu Jun 20 16:53:59 CST 2019
     */
    public void setTransitionid(Integer transitionid) {
        this.transitionid = transitionid;
    }
}