package sqldemo.model;
public class transition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transition.TransitionID
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    private Integer transitionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transition.Guide
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    private String guide;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transition.Name
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transition.triggerid
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    private Integer triggerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transition.TransitionID
     *
     * @return the value of transition.TransitionID
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    public Integer getTransitionid() {
        return transitionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transition.TransitionID
     *
     * @param transitionid the value for transition.TransitionID
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    public void setTransitionid(Integer transitionid) {
        this.transitionid = transitionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transition.Guide
     *
     * @return the value of transition.Guide
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    public String getGuide() {
        return guide;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transition.Guide
     *
     * @param guide the value for transition.Guide
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    public void setGuide(String guide) {
        this.guide = guide == null ? null : guide.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transition.Name
     *
     * @return the value of transition.Name
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transition.Name
     *
     * @param name the value for transition.Name
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transition.triggerid
     *
     * @return the value of transition.triggerid
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    public Integer getTriggerid() {
        return triggerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transition.triggerid
     *
     * @param triggerid the value for transition.triggerid
     *
     * @mbg.generated Thu Jun 20 18:11:56 CST 2019
     */
    public void setTriggerid(Integer triggerid) {
        this.triggerid = triggerid;
    }
}